import {
  AnalysisLaunchWizard,
  AnalysisRunConsole,
  AccountSummaryHero,
  AccountsGrid,
  ConfigInspector,
  CycleBoard,
  MemoryRecordList,
  ScanResultsBoard,
  ScanWorkbench,
  StrategyLibraryBoard,
  TradeDeskWorkspace,
} from "./composites";
import { NeuChartCard, NeuChartToolbar, NeuLegendChip } from "./charts";
import {
  NeuBadge,
  NeuCard,
  NeuEmptyState,
  NeuFilterBar,
  NeuKpiGrid,
  NeuPagination,
  NeuProgressTrack,
  NeuScoreBar,
  NeuSkeleton,
  NeuTable,
  NeuTickerMetric,
} from "./display";
import {
  NeuDivider,
  NeuGlowAccent,
  NeuPanel,
  NeuSurface,
  NeuThemeScope,
  NeuWell,
} from "./foundation";
import {
  NeuEntityHeader,
  NeuPageHeader,
  NeuStatCapsule,
  NeuStatusPill,
} from "./headers";
import {
  NeuAccountPicker,
  NeuButton,
  NeuCheckbox,
  NeuCombobox,
  NeuDateField,
  NeuIconButton,
  NeuInput,
  NeuModelPicker,
  NeuMultiSelect,
  NeuRadioGroup,
  NeuSelect,
  NeuSlider,
  NeuSwitch,
  NeuTabs,
  NeuTextArea,
  NeuToggleGroup,
} from "./inputs";
import {
  NeuBanner,
  NeuConfirmDialog,
  NeuDialog,
  NeuDrawer,
  NeuReconnectionChip,
  NeuToast,
} from "./overlays";
import {
  NeuAlertStack,
  NeuFormGrid,
  NeuFormSection,
  NeuPageSection,
  NeuRouteModelCard,
  NeuSplitLayout,
  NeuTouchActionBar,
} from "./structure";
import {
  NeuAnalyticsTemplate,
  NeuArchiveTemplate,
  NeuConsoleTemplate,
  NeuEntityDetailTemplate,
  NeuInspectorTemplate,
  NeuLibraryTemplate,
  NeuOverviewTemplate,
  NeuPortfolioGridTemplate,
  NeuTableIndexTemplate,
  NeuWizardTemplate,
  NeuWorkbenchTemplate,
} from "./templates";
import {
  NeuAppShell,
  NeuAppearanceStudio,
  NeuCommandPalette,
  NeuMarketStrip,
  NeuMobileDock,
  NeuNavItem,
  NeuSidebar,
  NeuTopbar,
} from "./shell";

export const neumorphismComponentRegistry = {
  NeuThemeScope,
  NeuSurface,
  NeuPanel,
  NeuWell,
  NeuDivider,
  NeuGlowAccent,
  NeuPageSection,
  NeuFormGrid,
  NeuFormSection,
  NeuSplitLayout,
  NeuAlertStack,
  NeuTouchActionBar,
  NeuRouteModelCard,
  NeuAppShell,
  NeuSidebar,
  NeuNavItem,
  NeuTopbar,
  NeuMarketStrip,
  NeuMobileDock,
  NeuCommandPalette,
  NeuAppearanceStudio,
  NeuPageHeader,
  NeuEntityHeader,
  NeuStatCapsule,
  NeuStatusPill,
  NeuButton,
  NeuIconButton,
  NeuInput,
  NeuTextArea,
  NeuSelect,
  NeuMultiSelect,
  NeuCombobox,
  NeuToggleGroup,
  NeuTabs,
  NeuCheckbox,
  NeuRadioGroup,
  NeuSlider,
  NeuSwitch,
  NeuDateField,
  NeuModelPicker,
  NeuAccountPicker,
  NeuCard,
  NeuBadge,
  NeuTable,
  NeuFilterBar,
  NeuEmptyState,
  NeuSkeleton,
  NeuPagination,
  NeuKpiGrid,
  NeuTickerMetric,
  NeuScoreBar,
  NeuProgressTrack,
  NeuChartCard,
  NeuChartToolbar,
  NeuLegendChip,
  NeuDialog,
  NeuDrawer,
  NeuToast,
  NeuBanner,
  NeuReconnectionChip,
  NeuConfirmDialog,
  AnalysisLaunchWizard,
  AnalysisRunConsole,
  ScanWorkbench,
  ScanResultsBoard,
  AccountsGrid,
  AccountSummaryHero,
  TradeDeskWorkspace,
  StrategyLibraryBoard,
  CycleBoard,
  ConfigInspector,
  MemoryRecordList,
  NeuOverviewTemplate,
  NeuWizardTemplate,
  NeuConsoleTemplate,
  NeuArchiveTemplate,
  NeuWorkbenchTemplate,
  NeuPortfolioGridTemplate,
  NeuEntityDetailTemplate,
  NeuAnalyticsTemplate,
  NeuLibraryTemplate,
  NeuTableIndexTemplate,
  NeuInspectorTemplate,
} as const;

export const neumorphismComponentChecklist = {
  foundations: ["NeuSurface", "NeuPanel", "NeuWell", "NeuDivider", "NeuGlowAccent"],
  structure: [
    "NeuPageSection",
    "NeuFormGrid",
    "NeuFormSection",
    "NeuSplitLayout",
    "NeuAlertStack",
    "NeuTouchActionBar",
    "NeuRouteModelCard",
  ],
  shell: [
    "NeuAppShell",
    "NeuSidebar",
    "NeuNavItem",
    "NeuTopbar",
    "NeuMarketStrip",
    "NeuMobileDock",
    "NeuCommandPalette",
    "NeuAppearanceStudio",
  ],
  headers: ["NeuPageHeader", "NeuEntityHeader", "NeuStatCapsule", "NeuStatusPill"],
  inputs: [
    "NeuButton",
    "NeuIconButton",
    "NeuInput",
    "NeuTextArea",
    "NeuSelect",
    "NeuMultiSelect",
    "NeuCombobox",
    "NeuToggleGroup",
    "NeuTabs",
    "NeuCheckbox",
    "NeuRadioGroup",
    "NeuSlider",
    "NeuSwitch",
    "NeuDateField",
    "NeuModelPicker",
    "NeuAccountPicker",
  ],
  display: [
    "NeuCard",
    "NeuBadge",
    "NeuTable",
    "NeuFilterBar",
    "NeuEmptyState",
    "NeuSkeleton",
    "NeuPagination",
    "NeuKpiGrid",
    "NeuTickerMetric",
    "NeuScoreBar",
    "NeuProgressTrack",
  ],
  charts: ["NeuChartCard", "NeuChartToolbar", "NeuLegendChip"],
  overlays: ["NeuDialog", "NeuDrawer", "NeuToast", "NeuBanner", "NeuReconnectionChip", "NeuConfirmDialog"],
  composites: [
    "AnalysisLaunchWizard",
    "AnalysisRunConsole",
    "ScanWorkbench",
    "ScanResultsBoard",
    "AccountsGrid",
    "AccountSummaryHero",
    "TradeDeskWorkspace",
    "StrategyLibraryBoard",
    "CycleBoard",
    "ConfigInspector",
    "MemoryRecordList",
  ],
  templates: [
    "NeuOverviewTemplate",
    "NeuWizardTemplate",
    "NeuConsoleTemplate",
    "NeuArchiveTemplate",
    "NeuWorkbenchTemplate",
    "NeuPortfolioGridTemplate",
    "NeuEntityDetailTemplate",
    "NeuAnalyticsTemplate",
    "NeuLibraryTemplate",
    "NeuTableIndexTemplate",
    "NeuInspectorTemplate",
  ],
} as const;
