import type { NeuRouteLayoutModel } from "./types";

export const neumorphismRouteLayoutModels: NeuRouteLayoutModel[] = [
  {
    route: "/",
    title: "Home dashboard",
    navSection: "Overview",
    template: "NeuOverviewTemplate",
    headerVariant: "overview",
    desktopZones: [
      { id: "hero", label: "Hero summary", description: "Launch actions, KPI hero, and current market posture.", emphasis: "primary" },
      { id: "research", label: "Research modules", description: "Analysis, scanner, and active run cards in a dense working stack.", emphasis: "primary" },
      { id: "aside", label: "Operational aside", description: "Runtime health, portfolio pulse, and recent activity.", emphasis: "supporting" },
    ],
    mobileZones: [
      { id: "stack", label: "Single-scroll deck", description: "Hero, activity, and modules collapse into one thumb-friendly column.", emphasis: "primary" },
      { id: "dock", label: "Bottom dock", description: "Fast switches for home, analysis, scanner, and accounts.", emphasis: "actions" },
      { id: "drawer", label: "Quick action drawer", description: "Secondary controls and filters move into a bottom sheet.", emphasis: "secondary" },
    ],
    alerts: ["Queue health", "Runtime latency"],
    drawers: ["Quick actions", "Command palette"],
    touchActions: ["Launch analysis", "Open scanner", "Resume run"],
  },
  {
    route: "/analysis/new",
    title: "Analysis wizard",
    navSection: "Research",
    template: "NeuWizardTemplate",
    headerVariant: "wizard",
    desktopZones: [
      { id: "steps", label: "Step rail", description: "Persistent progress rail with current stage and validation state.", emphasis: "secondary" },
      { id: "form", label: "Primary form", description: "Dense analysis inputs, pickers, and advanced options.", emphasis: "primary" },
      { id: "summary", label: "Summary rail", description: "Selected provider, models, and risk-sensitive launch notes.", emphasis: "supporting" },
    ],
    mobileZones: [
      { id: "stack", label: "Stacked stages", description: "Step rail compresses to chips above the form sections.", emphasis: "primary" },
      { id: "sheet", label: "Advanced settings sheet", description: "Vendor, overrides, and watchlists move into drawers.", emphasis: "secondary" },
      { id: "cta", label: "Sticky launch bar", description: "Save draft and run actions stay fixed near the bottom edge.", emphasis: "actions" },
    ],
    alerts: ["Missing credentials", "Risk lock warning"],
    drawers: ["Advanced settings", "Model overrides"],
    touchActions: ["Continue", "Save draft", "Run analysis"],
  },
  {
    route: "/analysis/$runId",
    title: "Analysis run console",
    navSection: "Research",
    template: "NeuConsoleTemplate",
    headerVariant: "console",
    desktopZones: [
      { id: "status", label: "Status rail", description: "Connection state, run health, and progress banners.", emphasis: "secondary" },
      { id: "primary", label: "Message and stream pane", description: "Live agent messages and timeline activity.", emphasis: "primary" },
      { id: "reports", label: "Reports and outputs", description: "Generated report panels and supporting stats.", emphasis: "primary" },
    ],
    mobileZones: [
      { id: "stack", label: "Priority stack", description: "Run status, messages, and reports stack in execution order.", emphasis: "primary" },
      { id: "drawer", label: "Agent roster drawer", description: "Secondary diagnostics and config summary move into a side sheet.", emphasis: "secondary" },
      { id: "cta", label: "Runtime action bar", description: "Retry, stop, and export remain easy to reach with one hand.", emphasis: "actions" },
    ],
    alerts: ["Disconnected stream", "Agent failure"],
    drawers: ["Agent roster", "Run config"],
    touchActions: ["Reconnect", "Export report", "Stop run"],
  },
  {
    route: "/history",
    title: "Analysis archive",
    navSection: "Research",
    template: "NeuArchiveTemplate",
    headerVariant: "archive",
    desktopZones: [
      { id: "filters", label: "Archive filters", description: "Search, chips, sort, and bulk actions across the index.", emphasis: "secondary" },
      { id: "results", label: "Archive results", description: "Dense table/list surface with history metadata and actions.", emphasis: "primary" },
      { id: "pagination", label: "Pagination rail", description: "Paging and result density controls.", emphasis: "supporting" },
    ],
    mobileZones: [
      { id: "chip-row", label: "Collapsible filters", description: "Filter controls collapse to a smaller stacked toolbar.", emphasis: "secondary" },
      { id: "cards", label: "Stacked archive cards", description: "Rows become touch-friendly record cards.", emphasis: "primary" },
      { id: "drawer", label: "Bulk action drawer", description: "Multi-select actions move off the main list.", emphasis: "actions" },
    ],
    alerts: ["Stale run", "Deleted history"],
    drawers: ["Bulk actions"],
    touchActions: ["Open run", "Delete record", "Filter results"],
  },
  {
    route: "/scanner",
    title: "Scanner workbench",
    navSection: "Research",
    template: "NeuWorkbenchTemplate",
    headerVariant: "workbench",
    desktopZones: [
      { id: "controls", label: "Scan controls", description: "Universe, cadence, analyst mix, and execution settings.", emphasis: "primary" },
      { id: "results", label: "Result board", description: "Grouped opportunities and table results.", emphasis: "primary" },
      { id: "aside", label: "Job aside", description: "Recent runs, queue state, and schedule shortcuts.", emphasis: "supporting" },
    ],
    mobileZones: [
      { id: "stack", label: "Controls first stack", description: "Configuration and results flow vertically for touch use.", emphasis: "primary" },
      { id: "sheet", label: "Auto-trade drawer", description: "Advanced automation settings live in a sheet.", emphasis: "secondary" },
      { id: "cta", label: "Sticky scan controls", description: "Run, stop, and schedule remain fixed near the thumb zone.", emphasis: "actions" },
    ],
    alerts: ["Active scan", "Trade automation risk"],
    drawers: ["Auto-trade settings", "Schedule setup"],
    touchActions: ["Start scan", "Stop scan", "Schedule scan"],
  },
  {
    route: "/scanner/history",
    title: "Scan archive",
    navSection: "Research",
    template: "NeuArchiveTemplate",
    headerVariant: "archive",
    desktopZones: [
      { id: "filters", label: "Scan filters", description: "History filters, statuses, and search.", emphasis: "secondary" },
      { id: "cards", label: "Scan records", description: "Result cards with run state, score mix, and actions.", emphasis: "primary" },
      { id: "pagination", label: "Paging bar", description: "Archive density and pagination controls.", emphasis: "supporting" },
    ],
    mobileZones: [
      { id: "stack", label: "Record stack", description: "Scan records convert to larger tap-ready cards.", emphasis: "primary" },
      { id: "drawer", label: "History filter sheet", description: "Less-frequent filter controls shift into a drawer.", emphasis: "secondary" },
      { id: "cta", label: "Quick rescan bar", description: "Return-to-scan and rerun stay pinned in compact layouts.", emphasis: "actions" },
    ],
    alerts: ["Running scan", "Failed scan"],
    drawers: ["History filters"],
    touchActions: ["Open scan", "Rerun scan", "Delete scan"],
  },
  {
    route: "/scanner/schedules",
    title: "Scheduled scans",
    navSection: "Research",
    template: "NeuWorkbenchTemplate",
    headerVariant: "workbench",
    desktopZones: [
      { id: "index", label: "Schedule index", description: "Existing schedules with health state and edit actions.", emphasis: "primary" },
      { id: "builder", label: "Schedule builder", description: "Create/edit dialog or side panel for timing and payload settings.", emphasis: "secondary" },
      { id: "aside", label: "Runtime aside", description: "Last-run status, queue pressure, and automation notes.", emphasis: "supporting" },
    ],
    mobileZones: [
      { id: "cards", label: "Schedule cards", description: "Schedules convert to stacked cards with strong action rows.", emphasis: "primary" },
      { id: "sheet", label: "Full-height schedule sheet", description: "Create/edit form becomes a mobile drawer.", emphasis: "secondary" },
      { id: "cta", label: "Sticky save bar", description: "Save, pause, and run-now stay pinned during editing.", emphasis: "actions" },
    ],
    alerts: ["Disabled schedule", "Missed run"],
    drawers: ["Create schedule", "Edit schedule"],
    touchActions: ["Create", "Pause", "Run now"],
  },
  {
    route: "/scanner/$scanId",
    title: "Scan detail",
    navSection: "Research",
    template: "NeuEntityDetailTemplate",
    headerVariant: "detail",
    desktopZones: [
      { id: "summary", label: "Detail summary", description: "Header stats, run state, and scan meta.", emphasis: "secondary" },
      { id: "results", label: "Result groups", description: "Buy/sell/hold result boards and sortable tables.", emphasis: "primary" },
      { id: "aside", label: "Action rail", description: "Deep links to analysis, trade, and cycle creation.", emphasis: "actions" },
    ],
    mobileZones: [
      { id: "stack", label: "Tabbed result stack", description: "Summary and grouped results become stackable sections.", emphasis: "primary" },
      { id: "drawer", label: "Action drawer", description: "Trade and cycle flows move into a side sheet.", emphasis: "actions" },
      { id: "cta", label: "Bottom action bar", description: "High-frequency actions stay thumb reachable.", emphasis: "actions" },
    ],
    alerts: ["Scan running", "Result drift"],
    drawers: ["Trade action drawer", "Cycle creation drawer"],
    touchActions: ["View analysis", "Open trade", "Create cycle"],
  },
  {
    route: "/accounts",
    title: "Accounts dashboard",
    navSection: "Portfolio",
    template: "NeuPortfolioGridTemplate",
    headerVariant: "portfolio",
    desktopZones: [
      { id: "hero", label: "Portfolio hero", description: "Aggregate balance, PnL, and account filters.", emphasis: "primary" },
      { id: "grid", label: "Account grid", description: "Live and demo account cards with actions.", emphasis: "primary" },
      { id: "aside", label: "Portfolio utilities", description: "Connection status, summaries, and bulk actions.", emphasis: "supporting" },
    ],
    mobileZones: [
      { id: "stack", label: "Account stack", description: "Cards become larger touch surfaces with clearer CTAs.", emphasis: "primary" },
      { id: "sheet", label: "Bulk action sheet", description: "Reset, add, and close-all move to a drawer.", emphasis: "actions" },
      { id: "dock", label: "Portfolio dock shortcuts", description: "Fast jumps back to analytics and trades remain visible.", emphasis: "actions" },
    ],
    alerts: ["Margin warning", "Exchange disconnected"],
    drawers: ["Add account", "Close-all positions"],
    touchActions: ["Open account", "Add account", "Reset demo"],
  },
  {
    route: "/accounts/$accountId",
    title: "Account detail",
    navSection: "Portfolio",
    template: "NeuEntityDetailTemplate",
    headerVariant: "detail",
    desktopZones: [
      { id: "hero", label: "Account hero", description: "Wallet summary, account health, and key actions.", emphasis: "primary" },
      { id: "content", label: "Positions and activity", description: "Tabs or sectional layout for positions, orders, and analytics.", emphasis: "primary" },
      { id: "aside", label: "Credential and risk rail", description: "Sensitive actions and side metrics.", emphasis: "actions" },
    ],
    mobileZones: [
      { id: "stack", label: "Section stack", description: "Wallet summary, positions, and analytics become swipe-friendly sections.", emphasis: "primary" },
      { id: "drawer", label: "Sensitive action drawer", description: "Rotate credentials and delete account move off the main canvas.", emphasis: "actions" },
      { id: "cta", label: "Position action bar", description: "Close, hedge, and reconcile remain bottom-anchored.", emphasis: "actions" },
    ],
    alerts: ["Liquidation proximity", "Credential stale"],
    drawers: ["Sensitive actions", "Analytics filters"],
    touchActions: ["Close position", "Reconcile", "Rotate credentials"],
  },
  {
    route: "/analytics",
    title: "Analytics dashboard",
    navSection: "Portfolio",
    template: "NeuAnalyticsTemplate",
    headerVariant: "analytics",
    desktopZones: [
      { id: "controls", label: "Control shelf", description: "Period, account, snapshot, and cleanup actions.", emphasis: "secondary" },
      { id: "charts", label: "Chart field", description: "Equity curve, drawdown, and PnL analysis.", emphasis: "primary" },
      { id: "aside", label: "Insight rail", description: "Benchmarks, anomalies, and monthly snapshots.", emphasis: "supporting" },
    ],
    mobileZones: [
      { id: "stack", label: "Chart-first stack", description: "KPI shelf and charts become vertically scrollable surfaces.", emphasis: "primary" },
      { id: "sheet", label: "Filter drawer", description: "Period/account controls collapse into a drawer.", emphasis: "secondary" },
      { id: "cta", label: "Snapshot action bar", description: "Snapshot and cleanup stay pinned in tighter widths.", emphasis: "actions" },
    ],
    alerts: ["Snapshot stale", "Cleanup recommended"],
    drawers: ["Filter drawer", "Benchmark compare"],
    touchActions: ["Snapshot", "Change period", "Cleanup"],
  },
  {
    route: "/strategies",
    title: "Strategy library",
    navSection: "Portfolio",
    template: "NeuLibraryTemplate",
    headerVariant: "library",
    desktopZones: [
      { id: "filters", label: "Library filters", description: "Search, category, status, import, and export actions.", emphasis: "secondary" },
      { id: "grid", label: "Strategy grid", description: "Searchable strategy cards with CRUD actions.", emphasis: "primary" },
      { id: "dialog", label: "Create/edit overlays", description: "Dedicated form dialogs for strategy editing.", emphasis: "actions" },
    ],
    mobileZones: [
      { id: "stack", label: "Scrollable card library", description: "Strategies become larger cards with clearer action rows.", emphasis: "primary" },
      { id: "drawer", label: "Filter and form sheets", description: "Filters and edit forms move into drawers.", emphasis: "secondary" },
      { id: "cta", label: "Library action bar", description: "Create, import, and export stay reachable at the bottom.", emphasis: "actions" },
    ],
    alerts: ["Strategy validation", "Import conflict"],
    drawers: ["Create strategy", "Filter library"],
    touchActions: ["Create", "Edit", "Duplicate"],
  },
  {
    route: "/cycles",
    title: "Cycle index",
    navSection: "Portfolio",
    template: "NeuTableIndexTemplate",
    headerVariant: "table",
    desktopZones: [
      { id: "toolbar", label: "Cycle toolbar", description: "Search, filters, refresh, and pagination controls.", emphasis: "secondary" },
      { id: "table", label: "Cycle index", description: "Table/list view depending density and viewport.", emphasis: "primary" },
      { id: "aside", label: "Cycle support rail", description: "Refresh state, metrics, and saved filters.", emphasis: "supporting" },
    ],
    mobileZones: [
      { id: "cards", label: "Cycle cards", description: "Table rows convert to card layout with summary metrics.", emphasis: "primary" },
      { id: "drawer", label: "Filter sheet", description: "Advanced filters shift into a drawer.", emphasis: "secondary" },
      { id: "cta", label: "Refresh action bar", description: "Refresh and open-detail actions stay sticky.", emphasis: "actions" },
    ],
    alerts: ["Active cycle", "Failed cycle"],
    drawers: ["Cycle filters"],
    touchActions: ["Open cycle", "Refresh", "Filter"],
  },
  {
    route: "/cycles/$cycleId",
    title: "Cycle detail",
    navSection: "Portfolio",
    template: "NeuEntityDetailTemplate",
    headerVariant: "detail",
    desktopZones: [
      { id: "hero", label: "Cycle hero", description: "Status, risk, symbol, and active controls.", emphasis: "primary" },
      { id: "sections", label: "Execution detail", description: "Trade tables, metrics, and automation status.", emphasis: "primary" },
      { id: "aside", label: "Cycle side rail", description: "Stop cycle actions and related activity.", emphasis: "actions" },
    ],
    mobileZones: [
      { id: "stack", label: "Execution stack", description: "Hero, stats, and trades stack with stronger section markers.", emphasis: "primary" },
      { id: "drawer", label: "Control drawer", description: "Stop cycle and diagnostic utilities move into a sheet.", emphasis: "actions" },
      { id: "cta", label: "Cycle action bar", description: "High-frequency controls stay pinned for one-hand access.", emphasis: "actions" },
    ],
    alerts: ["Cycle blocked", "Automation paused"],
    drawers: ["Cycle controls"],
    touchActions: ["Stop cycle", "Refresh", "Open trade"],
  },
  {
    route: "/config",
    title: "Runtime inspector",
    navSection: "System",
    template: "NeuInspectorTemplate",
    headerVariant: "inspector",
    desktopZones: [
      { id: "controls", label: "Appearance and scope controls", description: "Theme controls and view-scoping utilities.", emphasis: "secondary" },
      { id: "inspector", label: "Resolved configuration", description: "Settings tables, masked secrets, and overrides.", emphasis: "primary" },
      { id: "aside", label: "Operational notes", description: "Connectivity caveats and supporting annotations.", emphasis: "supporting" },
    ],
    mobileZones: [
      { id: "stack", label: "Inspector stack", description: "Appearance controls lead into config sections.", emphasis: "primary" },
      { id: "drawer", label: "Detail drawer", description: "Long-value inspection and notes move off the main list.", emphasis: "secondary" },
      { id: "cta", label: "Apply/review bar", description: "Apply and restore actions remain pinned.", emphasis: "actions" },
    ],
    alerts: ["Missing env var", "Override active"],
    drawers: ["Config notes", "Appearance controls"],
    touchActions: ["Inspect value", "Apply theme", "Restore defaults"],
  },
  {
    route: "/memory",
    title: "Memory browser",
    navSection: "System",
    template: "NeuTableIndexTemplate",
    headerVariant: "table",
    desktopZones: [
      { id: "toolbar", label: "Memory toolbar", description: "Filters, query, and paging controls.", emphasis: "secondary" },
      { id: "records", label: "Decision records", description: "Structured index of confidence and status-tagged memory entries.", emphasis: "primary" },
      { id: "aside", label: "Saved views", description: "Optional notes and saved filter context.", emphasis: "supporting" },
    ],
    mobileZones: [
      { id: "cards", label: "Record cards", description: "Entries convert to readable cards with tags and actions.", emphasis: "primary" },
      { id: "drawer", label: "Filter drawer", description: "Filters and saved views move into a sheet.", emphasis: "secondary" },
      { id: "cta", label: "Paging action bar", description: "Paging and filter openers remain close to the thumb zone.", emphasis: "actions" },
    ],
    alerts: ["Review pending", "High-confidence change"],
    drawers: ["Memory filters"],
    touchActions: ["Open record", "Next page", "Filter"],
  },
  {
    route: "/trades",
    title: "Trade desk",
    navSection: "Portfolio",
    template: "NeuTableIndexTemplate",
    headerVariant: "table",
    desktopZones: [
      { id: "toolbar", label: "Trade toolbar", description: "Tabs, filters, and live/history switching.", emphasis: "secondary" },
      { id: "table", label: "Trade surfaces", description: "Live trades, history, and stat rails.", emphasis: "primary" },
      { id: "aside", label: "Trade detail rail", description: "Selected trade details, ws state, and close actions.", emphasis: "actions" },
    ],
    mobileZones: [
      { id: "stack", label: "Trade card stack", description: "Live and historical trades collapse into grouped cards.", emphasis: "primary" },
      { id: "drawer", label: "Trade detail drawer", description: "Selected trade details move into a right drawer.", emphasis: "secondary" },
      { id: "cta", label: "Close-action bar", description: "Close one or close all actions stay pinned.", emphasis: "actions" },
    ],
    alerts: ["WebSocket offline", "Position risk"],
    drawers: ["Trade detail", "Bulk close"],
    touchActions: ["Close trade", "View details", "Filter"],
  },
];
